version: '3.8'

services:
  chainlit:
    build:
      context: ../..
      dockerfile: docker/chainlit/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../../.env
    volumes:
      - ../../apps/chainlit:/app

  # mcp-server:
  #   build:
  #     context: ../..
  #     dockerfile: docker/mcp-server/Dockerfile
  #   ports:
  #     - "8002:8002"
  #   env_file:
  #     - ../../.env
  #   volumes:
  #     - ../../common/mcp:/app