version: '3.8'

services:
  chainlit:
    build:
      context: ../..
      dockerfile: docker/chainlit/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../../.env.production
    volumes:
      - ../../apps/chainlit:/app